package drools.rodzina;
import drools.rodzina.Osoba


rule "Init"
	when
	then
		Osoba maria          = new Osoba("Maria");
		Osoba ewa            = new Osoba("Ewa");
		Osoba agata          = new Osoba("Agata");
		Osoba anna           = new Osoba("Anna");
		Osoba agnieszka      = new Osoba("Agnieszka");
		Osoba beata          = new Osoba("Beata");
		Osoba iwona          = new Osoba("Iwona");
		Osoba joanna         = new Osoba("Joanna");
		Osoba piotr          = new Osoba("Piotr");
		Osoba adam           = new Osoba("Adam");
		Osoba marek          = new Osoba("Marek");
		Osoba robert         = new Osoba("Robert");
		Osoba jan            = new Osoba("Jan");
		Osoba krzysztof      = new Osoba("Krzysztof");
		Osoba radek          = new Osoba("Radek");
		Osoba darek          = new Osoba("Darek");
		Osoba tomek          = new Osoba("Tomek");
		Osoba jacek          = new Osoba("Jacek");

		insert(new Relacja(maria,marek,"rodzic"));
		insert(new Relacja(maria,agata,"rodzic"));
		insert(new Relacja(maria,jan,"rodzic"));
		insert(new Relacja(piotr,marek,"rodzic"));
		insert(new Relacja(piotr,agata,"rodzic"));
		insert(new Relacja(piotr,jan,"rodzic"));
		insert(new Relacja(ewa,anna,"rodzic"));
		insert(new Relacja(ewa,joanna,"rodzic"));
		insert(new Relacja(ewa,krzysztof,"rodzic"));
		insert(new Relacja(adam,anna,"rodzic"));
		insert(new Relacja(adam,joanna,"rodzic"));
		insert(new Relacja(adam,krzysztof,"rodzic"));
		insert(new Relacja(agata,radek,"rodzic"));
		insert(new Relacja(agata,beata,"rodzic"));
		insert(new Relacja(robert,radek,"rodzic"));
		insert(new Relacja(robert,beata,"rodzic"));
		insert(new Relacja(anna,darek,"rodzic"));
		insert(new Relacja(anna,tomek,"rodzic"));
		insert(new Relacja(jan,darek,"rodzic"));
		insert(new Relacja(jan,tomek,"rodzic"));
		insert(new Relacja(agnieszka,jacek,"rodzic"));
		insert(new Relacja(agnieszka,iwona,"rodzic"));
		insert(new Relacja(krzysztof,jacek,"rodzic"));
		insert(new Relacja(krzysztof,iwona,"rodzic"));
		System.out.println("zakonczono");
end


rule "Kobieta1"
when
    rela : Relacja(osoby[0].toString().endsWith("a"), osoby[0].getPlec() == Osoba.Plec.NIEZNANA)
then
    System.out.println(rela.osoby[0].toString());
    rela.osoby[0].setPlec(Osoba.Plec.KOBIETA);
    for(Relacja rel : rela.osoby[0].relacje) update(rel);
end



rule "Kobieta2"
when
    rela : Relacja(osoby[1].toString().endsWith("a"), osoby[1].getPlec() == Osoba.Plec.NIEZNANA)
then
    System.out.println(rela.osoby[1].toString());
    rela.osoby[1].setPlec(Osoba.Plec.KOBIETA);
    for(Relacja rel : rela.osoby[1].relacje) update(rel);
end


rule "Mezczyzna1"
when
    rela : Relacja(osoby[0].toString().endsWith("a") == false, osoby[0].getPlec() == Osoba.Plec.NIEZNANA)
then
    System.out.println(rela.osoby[0].toString());
    rela.osoby[0].setPlec(Osoba.Plec.MEZCZYZNA);
    for(Relacja rel : rela.osoby[0].relacje) update(rel);
end


rule "Mezczyzna2"
when
    rela : Relacja(osoby[1].toString().endsWith("a") == false, osoby[1].getPlec() == Osoba.Plec.NIEZNANA)
then
    System.out.println(rela.osoby[1].toString());
    rela.osoby[1].setPlec(Osoba.Plec.MEZCZYZNA);
    for(Relacja rel : rela.osoby[1].relacje) update(rel);
end


rule "Ojciec"
when
    rela : Relacja(osoby[0].toString().endsWith("a") == false, relacja.equals("rodzic"))
then
    insert(new Relacja(rela.osoby[0], rela.osoby[1], "ojciec"));
    System.out.println(rela.osoby[0].toString()+" " + rela.osoby[1].toString() + " ojciec");
end

rule "Matka"
when
    rela : Relacja(osoby[0].toString().endsWith("a"), relacja.equals("rodzic"))
then
    insert(new Relacja(rela.osoby[0], rela.osoby[1], "matka"));
    System.out.println(rela.osoby[0].toString() + " "+rela.osoby[1].toString() +  " matka");
end


rule "Dziadek"
when
    rela1 : Relacja(relacja.equals("ojciec"))
    rela2 : Relacja(relacja.equals("rodzic"), rela2.osoby[0] == rela1.osoby[1])
then
    insert(new Relacja(rela1.osoby[0], rela2.osoby[1], "dziadek"));
    System.out.println(rela1.osoby[0].toString() + " " + rela2.osoby[1].toString() + " dziadek");
end


rule "Babcia"
when
    rela1 : Relacja(relacja.equals("matka"))
    rela2 : Relacja(relacja.equals("rodzic"), rela2.osoby[0] == rela1.osoby[1])
then
    insert(new Relacja(rela1.osoby[0], rela2.osoby[1], "dziadek"));
    System.out.println(rela1.osoby[0].toString() + " " + rela2.osoby[1].toString() + " babcia");
end

rule "Brat"
when
    rela1 : Relacja(relacja.equals("ojciec"), rela1.osoby[1].getPlec() == Osoba.Plec.MEZCZYZNA)
    rela2 : Relacja(relacja.equals("ojciec"), rela2.osoby[1] != rela1.osoby[1], rela1.osoby[0] == rela2.osoby[0])
then
    insert(new Relacja(rela1.osoby[1], rela2.osoby[1], "brat"));
    System.out.println(rela1.osoby[1].toString() + " " + rela2.osoby[1].toString() + " brat");
end


rule "Siostra"
when
    rela1 : Relacja(relacja.equals("ojciec"), rela1.osoby[1].getPlec() == Osoba.Plec.KOBIETA)
    rela2 : Relacja(relacja.equals("ojciec"), rela2.osoby[1] != rela1.osoby[1], rela1.osoby[0] == rela2.osoby[0])
then
    insert(new Relacja(rela1.osoby[1], rela2.osoby[1], "siostra"));
    System.out.println(rela1.osoby[1].toString() + " " + rela2.osoby[1].toString() + " siostra");
end


rule "Stryj"
when
    rela1 : Relacja(relacja.equals("brat"))
    rela2 : Relacja(relacja.equals("ojciec"), rela1.osoby[1] == rela2.osoby[0])
then
    insert(new Relacja(rela1.osoby[0], rela2.osoby[1], "stryj"));
    System.out.println(rela1.osoby[0].toString() + " " + rela2.osoby[1].toString() + " stryj");
end


rule "Wuj"
when
    rela1 : Relacja(relacja.equals("brat"))
    rela2 : Relacja(relacja.equals("matka"), rela1.osoby[1] == rela2.osoby[0])
then
    insert(new Relacja(rela1.osoby[0], rela2.osoby[1], "wuj"));
    //System.out.println(rela1.osoby[0].toString() + " " + rela1.osoby[1].toString() + " " + rela2.osoby[0].toString() + " " + rela2.osoby[1].toString() + " wuj");
    System.out.println(rela1.osoby[0].toString() + " " + rela2.osoby[1].toString() + " wuj");
end


query "Wujowie" (String siostrzeni_ec_ca)
    rela : Relacja(relacja.equals("wuj"), rela.osoby[1].toString() == siostrzeni_ec_ca)
end

query "Stryjkowie" (String braten_ek_ica)
    rela : Relacja(relacja.equals("stryj"), rela.osoby[1].toString() == braten_ek_ica)
end


rule "Kuzyn"
when
    rela1 : Relacja(relacja.equals("dziadek"), rela1.osoby[1].getPlec() == Osoba.Plec.MEZCZYZNA)
    rela2 : Relacja(relacja.equals("dziadek"), rela2.osoby[1] != rela1.osoby[1], rela1.osoby[0] == rela2.osoby[0])
    not Relacja(relacja.equals("brat"), rela1.osoby[1]==osoby[0], rela2.osoby[1]==osoby[1])
then
    insert(new Relacja(rela1.osoby[1], rela2.osoby[1], "kuzyn"));
    System.out.println(rela1.osoby[1].toString() + " " + rela2.osoby[1].toString() + " kuzyn");;
end


rule "Kuzynka"
when
    rela1 : Relacja(relacja.equals("dziadek"), rela1.osoby[1].getPlec() == Osoba.Plec.KOBIETA)
    rela2 : Relacja(relacja.equals("dziadek"), rela2.osoby[1] != rela1.osoby[1], rela1.osoby[0] == rela2.osoby[0])
    not Relacja(relacja.equals("siostra"), rela1.osoby[1]==osoby[0], rela2.osoby[1]==osoby[1])
then
    insert(new Relacja(rela1.osoby[1], rela2.osoby[1], "kuzynka"));
    System.out.println(rela1.osoby[1].toString() + " " + rela2.osoby[1].toString() + " kuzynka");
end