package rules
import java.util.Scanner;
import music.Question;
import music.Question.Answer;
import music.Controller;
dialect  "mvel"


declare FIXED
    f : Boolean
end


rule "INIT"
when
then
    insert(Controller.loadQuestion(1));
end


rule "AskQuestion"
when
    qu : Question(q != null, a == Answer.NONE)
then
    if(qu.advice != null) System.out.println(qu.advice);
    if(qu.q != null) {
        System.out.println(qu.q);
        System.out.print(">> ");
        Scanner keyboard = new Scanner(System.in);
        String answer = keyboard.nextLine();
        if(answer == "y" || answer == "yes") qu.a = Answer.YES;
        else qu.a = Answer.NO;
        update(qu);
    }
end

rule "ShowFinalAdvice"
when
    qu : Question(q == null)
then
    System.out.println(qu.advice);
    insert(new FIXED())
end

rule "IsFixed"
when
    FIXED()
then
    System.out.println("Diagnosis finished.");
end